### ISSUE TITLE
Homepage error when no current_user

### ISSUE THREAD

**Issue by jarredt** [yhordi/ShiftSlot#17]
**Issue**: When there is no current_user, visiting the root (localhost:3000 on dev) causes NoMethodError. Stack trace attached.

Looks like Landings#index is calling `Show.available_shifts_for(current_user)`, but if there's no user logged in then current_user is nil. `Show#available_shifts_for` calls `Show#already_working?`, which looks at the `id` of the user passed to it, so that's causing the error.

(I registered a new user and logged in, and homepage displayed w/o issue).

**Steps to reproduce:**

1. clone --> `bundle install` --> `be rake db:setup` --> `be rails s`
2. Visit `localhost:3000`

**Expected**: See homepage when visiting as logged-out user.

**Actual**: NoMethodError (see screenshot).

**Possible Fix**: Have Landings#index check if there's a logged-in user, and if not just set `@shifts` to be an empty array and skip the #available_shifts check.

<img width="679" alt="screen shot 2017-09-12 at 8 42 02 pm" src="https://user-images.githubusercontent.com/16692671/30358816-c8c939da-97fb-11e7-8e9c-4f8c85552ef7.png">

**Comment by jarredt** [comment]
(probably not able to take a stab at a fix for at least a few days, so wanted to note the issue in case anyone else wanted to fix earlier)

**Comment by yhordi** [comment]
@jarredt there should be some stock users in seeds.rb that'll get you past this issue, though this is certainly something to consider going forward. I'll keep this open for the time being.

**Comment by jarredt** [comment]
@yhordi yeah -- I seeded the database, but the issue occurs when there is no _logged in_ user. if I go to the root without being logged-in (i.e. as non-registered visitor when i spun up the server for the first time and visited root), I get the error above, due to there being no `current_user` to read an `id` from in the described methods.

**Comment by yhordi** [comment]
Gotcha, I'll fix this up :+1:
